### ISSUE TITLE
Bad substitution error on line 43 in ArchGen_cpp.sh

### ISSUE THREAD

**Issue by jay51** [Nrechati/ArchGen_Cpp#1]
I tried to generate a simple example this way `ArchGen A_myclass` but I got the above error
![image](https://imgur.com/mrzER3f.png)

I think the issue is in the readme <br /> `echo "alias <alias_name>="sh path-to-ArchGen_Cpp.sh"" >> ~/.zshrc` because you're executing the script with sh shell and in your script yoiu have ``` #!/bin/bash```, instead I would say just change this to `echo "alias <alias_name>=path-to-ArchGen_Cpp.sh" >> ~/.<your shell rc>` and keep bash as the default shell

**Comment by Nrechati** [comment]
Right, will fix it
[Edit]: fixed on master
